SELECT TOP 10 * FROM TB_ASSOCIADOS       --(LISTANDO O A TABELA TB_ASSOCIADOS)
SELECT TOP 10 * FROM TMKT..OPERADORES    --(PESQUISANDO O A TABELA OPERADORES, QUE SE ENCONTRA EM OUTRA BASE DE DADOS)

-- PODE-SE CONVERTE E FORMATAR A DATA E HORA, É SÓ ALTERAR O NÚMERO P( 103,102,104,ETC)
select TOP 10 convert(varchar,ASS_DATAHORA,103) as DEH_TESTE
FROM TB_ASSOCIADOS

-- MOSTRA DATA E HORA ATUAL. 
SELECT GETDATE()

-- SELECIONAR TODAS AS VENDAS DO DIA 25-04-2012 GVT_WEB, PORÉM SOMENTE TODOS SOMENTE OS REGISTROS QUE TENHAM ASS_STACODIGO IN (2,3)
--	MOSTRAR (NOME DO CLIENTE, NOME DO OPERADOR, DATA DA VENDA HORA DA VENDA)
SELECT DISTINCT NOME AS NOME_OPERADOR, ASS_NOME AS NOME_CLIENTE, CONVERT(VARCHAR, ASS_DATAHORA, 103) AS DATA_VENDA,
CONVERT(VARCHAR, ASS_DATAHORA, 108) AS HORA_VENDA
FROM TB_ASSOCIADOS INNER JOIN TMKT..OPERADORES WITH(NOLOCK)ON ASS_AGTCODIGO = NRREG
WHERE ASS_DATAHORA BETWEEN '2012-04-25' AND '2012-04-25 23:59:59' AND ASS_STACODIGO IN (2,3)

-- AGORA PESQUISAR QUANTAS VENDAS TEVE CADA CLIENTE E QUE TENHAM VENDAS MAIORES OU IGUAL A 2.
SELECT COUNT(ASS_NOME)AS QTDE_VENDAS, ASS_NOME AS NOME_CLIENTE
FROM TB_ASSOCIADOS INNER JOIN TMKT..OPERADORES WITH(NOLOCK)ON ASS_AGTCODIGO = NRREG
WHERE ASS_DATAHORA BETWEEN '2012-04-25' AND '2012-04-25 23:59:59' AND ASS_STACODIGO IN (2,3)
GROUP BY ASS_NOME
HAVING COUNT(ASS_NOME)> 1



