--É ATRAVES DO CLI_EASYCODE QUE PODEMOS PEGAR O CLI_CODIGO E VERIFICAR SE A VENDA JÁ ESTÁ GRAVADA. 
SELECT CLI_CODIGO, CLI_EASYCODE  FROM TB_CLIENTE 
WHERE CLI_EASYCODE  = 47605841

--VERIFICAR ATRAVES DO ASS_CLICODIGO SE A VENDA FOI REALIZADA E GRAVADA NA TABELA TB_ASSOCIADOS. 
SELECT * FROM TB_ASSOCIADOS
WHERE ASS_CLICODIGO = 68211


--(GERANDO UMA VENDA)
-- JÁ NO SANTANDER CAP
-- VERIFICANDO O CLI_CODIGO DO CLI_EASYCODE
SELECT CLI_CODIGO, CLI_EASYCODE FROM TB_CLIENTE
WHERE CLI_EASYCODE = 47500425

--VERIFICAR ATRAVES DO ASS_CLICODIGO SE A VENDA FOI REALIZADA E GRAVADA NA TABELA TB_ASSOCIADOS. 
SELECT * FROM TB_ASSOCIADOS
WHERE ASS_CLICODIGO = 4235394

SELECT TOP 10 * FROM TB_ASSOCIADOS
 

--OBS.SE NA HORA DE GRAVAR A VENDA DER ALGUMA MENSAGEM RELACIONADO A QUE O AUDITOR NÃO TEM PERMISSÃO
--PODE SER QUE O MESMO NEM TRABALHE MAIS NA EMPRESA E POR ISSO É BOM PROCURAR UM ADITOR QUE TENHA REALIZADO 
--UMA VENDA DE NO MÁXIMO UM DIA ANTERIOR. 
SELECT TOP 10 * FROM TB_ASSOCIADOS
WHERE ASS_STACODIGO IN (2,3) AND ASS_DATAAUDITORIA BETWEEN '2012-05-07' AND '2012-05-07 23:59:59'

-- ACHANDO A SENHA DO AUTIDOR
127486
SELECT SENHAUSU FROM TMKT..OPERADORES
WHERE NRREG = 127486

--GERANDO UMA SEGUNDA VENDA

SELECT CLI_CODIGO, CLI_EASYCODE FROM TB_CLIENTE
WHERE CLI_EASYCODE = 47228592

SELECT * FROM TB_ASSOCIADOS
WHERE ASS_CLICODIGO = 4030997

SELECT NOME, NRREG FROM TMKT..OPERADORES
WHERE NRREG = 833915

SELECT * FROM TB_ASSOCIADOS
WHERE ASS_STACODIGO IN (2,3) AND ASS_DATAAUDITORIA BETWEEN '2012-05-07' AND '2012-05-07 23:59:59'

127486
SELECT SENHAUSU FROM TMKT..OPERADORES
WHERE NRREG = 127486

--VERIICANDO NOVAMENTE SE A VENDA FOI GRAVADA COM SUCESSO. 
SELECT * FROM TB_ASSOCIADOS
WHERE ASS_CLICODIGO = 4030997

--(GERANDO UMA TERCEIRA VENDA)

SELECT CLI_CODIGO, CLI_EASYCODE FROM TB_CLIENTE
WHERE CLI_EASYCODE = 47479850

SELECT * FROM TB_ASSOCIADOS 
WHERE ASS_CLICODIGO = 4214970

SELECT NRREG, NOME FROM TMKT..OPERADORES
WHERE NRREG = 125913

SELECT * FROM TB_ASSOCIADOS
WHERE ASS_STACODIGO IN (2,3) AND ASS_DATAAUDITORIA BETWEEN '2012-05-07' AND '2012-05-07 23:59:59'

127486
SELECT SENHAUSU FROM TMKT..OPERADORES
WHERE NRREG = 127486

SELECT * FROM TB_ASSOCIADOS
WHERE ASS_CLICODIGO = 4214970














SELECT TOP 10 ASS_AUDITOR, SENHAUSU FROM TB_ASSOCIADOS
INNER JOIN TB_CLIENTE WITH(NOLOCK)
ON ASS_CLICODIGO = CLI_CODIGO
INNER JOIN TMKT..TB_CAMPANHA WITH(NOLOCK)
ON CLI_CMPCODIGO = CMP_CODIGO
INNER JOIN TMKT..OPERADORES WITH(NOLOCK)
ON ASS_AUDITOR = NRREG
WHERE CMP_ACOCODIGO = 841 AND ASS_DATAHORA >= '2012-04-20'
