Precisamos do histórico de ocorrências de todos os clientes do Santander Proteção Financeira de Agosto. Ação 841.

Nome, CPF, Todas as Ocorrências tabuladas(operador e discador), Data e Hora do contato.

Ex:Nome CPF 1ª Ocorrência Data Hora 2ª Ocorrência Data Hora 3ª Ocorrência Data Hora

--QUERY QUE GERA UM RELATÓRIO COM TODAS AS OCORRÊNCIAS, DATAS E HORAS DE CADA CLIENTE, CONFORME AÇÃO. (SANTANDER PROTEÇÃO - SANTANDER WEB) 
--EX:(CPF OCORRÂNCIA1 DATA1 HORA1  OCORRÂNCIA2 DATA2 HORA2 OCORRÊNCIA3 DATA3 HORA3 )


--CRIANDO A TABELA ONDE SERÃO ADICIONANDOS AS INFORMAÇÕES SOLICITADAS. 
CREATE TABLE RELATORIO_TESTE
(
	SEQ_REL INT,
	CPF    VARCHAR(20)
)

--CONTANDO AS QUANTIDADES DE CONTATOS DE CADA CLIENTE CORRESPONDETE AO MÊS DE AGOSTO E ADICIONANDO EM UMA TABELA TEMPORARIA. 
SELECT 
	DISTINCT
	COUNT(0) AS QTDE,	
	CTO_CLICODIGO,
	DDS_CPFCNPJ
	INTO #TEMP
 	FROM TB_CONTATO WITH(NOLOCK)
 	     INNER JOIN TB_CLIENTE WITH(NOLOCK) ON CTO_CLICODIGO = CLI_CODIGO 
		 INNER JOIN TMKT..TB_CAMPANHA WITH(NOLOCK) ON CMP_CODIGO = CLI_CMPCODIGO 
		 INNER JOIN TMKT..TB_ACAO WITH(NOLOCK) ON ACO_CODIGO = CMP_ACOCODIGO 
		 INNER JOIN TB_DADOSCLI WITH(NOLOCK) ON DDS_CLICODIGO = CLI_CODIGO 
		 WHERE ACO_CODIGO = 841 AND CTO_DATAHORA BETWEEN '2012-08-01 00:00:00' AND '2012-08-31 23:59:59'
		 GROUP BY CTO_CLICODIGO,DDS_CPFCNPJ 
         ORDER BY DDS_CPFCNPJ

			  
--ADICIONA COLUNAS A TABELA. 	
DECLARE @CONT INT
DECLARE @N INT
DECLARE @SQL VARCHAR(8000)
DECLARE @COLUNA VARCHAR(500)
DECLARE @DATA VARCHAR(500)
DECLARE @HORA VARCHAR(500)
DECLARE @D VARCHAR(10)
DECLARE @H VARCHAR(10)

SET @D = 1
SET @H = 1
SET @COLUNA = 'OCORRENCIA' 
SET @DATA = 'DATA'
SET @HORA = 'HORA'
SET @N = 1 
SET @CONT = 1
WHILE @CONT <= (SELECT MAX(QTDE) FROM #TEMP WITH(NOLOCK))
BEGIN
	SET @SQL = N'ALTER TABLE RELATORIO_TESTE ADD ['+ LTRIM(RTRIM(@COLUNA+CONVERT(VARCHAR,@N)))+'] VARCHAR(500),'
	SET @SQL = @SQL + '['+LTRIM(RTRIM(@DATA+CONVERT(VARCHAR, @D)))+'] VARCHAR(500),'
	SET @SQL = @SQL + '['+LTRIM(RTRIM(@HORA+CONVERT(VARCHAR, @H)))+'] VARCHAR(500)'
	

	--PRINT(@SQL)
	EXEC(@SQL)

		
    SET @CONT = @CONT + 1 
    SET @N = @N + 1 
    SET @D = @D + 1
    SET @H = @H + 1
END

CREATE TABLE ODH
(
	SEQ_ODH   INT IDENTITY (1,1),
	CPF VARCHAR(19),
	DESCRICAO VARCHAR(800),
	DATA VARCHAR(800),
	HORA VARCHAR(800)
)

CREATE TABLE CPFS 
(
	SEQ_CPF INT IDENTITY(1,1),
	QTDE INT,
	CPF VARCHAR(20),
	CLICODIGO INT
)


--INSERINDO NA TABELA CPFS, A QUANTIDADE DOS CÓDIGO E CPFS DOS CLIENTES.   
INSERT INTO CPFS(QTDE,CPF, CLICODIGO)
SELECT     
	DISTINCT 
	COUNT(0),
	DDS_CPFCNPJ AS CP,
	DDS_CLICODIGO AS CLIENTE
    FROM TB_CONTATO WITH(NOLOCK) INNER JOIN TB_OCORRENCIA WITH(NOLOCK) ON OCR_GRUPO = CTO_GRUPO AND OCR_SUBGRUPO = CTO_SUBGRUPO AND OCR_OCORRENCIA = CTO_OCORRENCIA 
								 INNER JOIN TB_DADOSCLI WITH(NOLOCK) ON DDS_CLICODIGO = CTO_CLICODIGO 
                                 WHERE CTO_CLICODIGO IN (SELECT DISTINCT CTO_CLICODIGO FROM TB_CONTATO WITH(NOLOCK) 
																							INNER JOIN TB_CLIENTE WITH(NOLOCK) ON CTO_CLICODIGO = CLI_CODIGO 
																							INNER JOIN TMKT..TB_CAMPANHA WITH(NOLOCK) ON CMP_CODIGO = CLI_CMPCODIGO 
																							INNER JOIN TMKT..TB_ACAO WITH(NOLOCK) ON ACO_CODIGO = CMP_ACOCODIGO 
																							WHERE ACO_CODIGO = 841 AND CTO_DATAHORA BETWEEN '2012-08-01 00:00:00' AND '2012-08-31 23:59:59')
    GROUP BY DDS_CPFCNPJ, DDS_CLICODIGO 
    ORDER BY DDS_CPFCNPJ 


--LISTA A TODAS AS OCORRENCIAS, DATAS E HORAS DE CADA CLIENTE LISTADO.     
DECLARE @CLICODIGOS INT
DECLARE @CONT_OCO INT
SET @CONT_OCO = 1
WHILE @CONT_OCO < = (SELECT COUNT(0) FROM #TEMP)
BEGIN	
		SELECT @CLICODIGOS = CLICODIGO FROM CPFS WHERE SEQ_CPF = @CONT_OCO
		
		INSERT INTO ODH (CPF,DESCRICAO, DATA, HORA)
		SELECT 
			DDS_CPFCNPJ AS CPF,
			OCR_DESCRICAO AS DESCRICAO,
			CONVERT(VARCHAR, CTO_DATAHORA, 103) AS DATA, 
			CONVERT(VARCHAR, CTO_DATAHORA, 108) AS HORA  
			FROM TB_CONTATO WITH(NOLOCK)
				 INNER JOIN TB_OCORRENCIA WITH(NOLOCK) ON OCR_GRUPO = CTO_GRUPO AND OCR_SUBGRUPO = CTO_SUBGRUPO AND OCR_OCORRENCIA = CTO_OCORRENCIA 
				 INNER JOIN TB_DADOSCLI WITH(NOLOCK) ON DDS_CLICODIGO = CTO_CLICODIGO
				 INNER JOIN CPFS WITH(NOLOCK)ON CLICODIGO = CTO_CLICODIGO 
				 WHERE CTO_CLICODIGO IN (@CLICODIGOS)
				 ORDER BY DDS_CPFCNPJ
	SET @CONT_OCO = @CONT_OCO + 1
END               
               

    
--COLOCA AS DESCRIÇÕES, DATAS, HORAS EM UMA VARIÁVEL E TUDO POR SEQUÊNCIA. 
DECLARE @CONTEUDO VARCHAR(8000)
DECLARE @CPF VARCHAR(20)
DECLARE @DESCRICAO VARCHAR(8000)
DECLARE @DATA VARCHAR(8000)
DECLARE @HORA VARCHAR(8000)
DECLARE @CONT2 INT
DECLARE @ON INT
DECLARE @DN INT
DECLARE @HN INT
DECLARE @CONT3 INT
DECLARE @LI INT


SET @ON  = 1
SET @DN = 1
SET @HN  = 1
SET @LI = 1
SET @CONT3 = 1
SET @CONT2 = 1
WHILE @CONT2 <=(SELECT COUNT(0) FROM CPFS WITH(NOLOCK))
BEGIN

	SELECT @CPF = CPF FROM CPFS WITH(NOLOCK) WHERE SEQ_CPF = @CONT2
	INSERT INTO RELATORIO_TESTE (SEQ_REL) VALUES (@CONT2)

SET @ON = 1 
SET @DN = 1
SET @HN = 1
SET @CONT3 = 1
	WHILE @CONT3 <= (SELECT QTDE FROM CPFS WITH(NOLOCK) WHERE SEQ_CPF = @CONT2)
	BEGIN


		SELECT @DESCRICAO = DESCRICAO FROM ODH WITH(NOLOCK) WHERE SEQ_ODH =  @LI ORDER BY CPF 
		SELECT @DATA = DATA FROM ODH WITH(NOLOCK) WHERE SEQ_ODH = @LI ORDER BY CPF 
		SELECT @HORA = HORA FROM ODH WITH(NOLOCK) WHERE SEQ_ODH = @LI ORDER BY CPF 
		

		SET @CONTEUDO = N'UPDATE RELATORIO_TESTE SET CPF = '''+@CPF+''', OCORRENCIA'+CONVERT(VARCHAR, @ON)+' ='''+LTRIM(RTRIM(@DESCRICAO))+''','
		SET @CONTEUDO = @CONTEUDO +'DATA'+CONVERT(VARCHAR, @DN)+'='''+LTRIM(RTRIM(@DATA))+ ''','
		SET @CONTEUDO = @CONTEUDO +'HORA'+CONVERT(VARCHAR, @HN)+'='''+LTRIM(RTRIM(@HORA))+''''
		SET @CONTEUDO = @CONTEUDO + 'WHERE CONVERT(VARCHAR, SEQ_REL) ='''+CONVERT(VARCHAR, @CONT2)+'''' --AND CPF = '''+@CPF+'''
       --SET @CONTEUDO = N'INSERT INTO RELATORIO_TESTE (OCORRENCIA'+CONVERT(VARCHAR, @ON)+', DATA'+CONVERT(VARCHAR, @DN)+', HORA'+CONVERT(VARCHAR, @HN)+') VALUES ('''+LTRIM(RTRIM(@DESCRICAO))+''','''+LTRIM(RTRIM(@DATA))+''', '''+LTRIM(RTRIM(@HORA))+''') '


   		--PRINT (@CONTEUDO) 
		EXEC (@CONTEUDO)
	    SET @LI = @LI + 1
		SET @ON = @ON + 1
		SET @DN = @DN + 1
		SET @HN = @HN + 1
        
		SET @CONT3 = @CONT3 + 1
    END
    
    SET @CONT2 = @CONT2 + 1
 
END
							
DROP TABLE CPFS
DROP TABLE ODH
DROP TABLE #TEMP
DROP TABLE RELATORIO_TESTE
SELECT * FROM RELATORIO_TESTE
SELECT * FROM ODH
SELECT * FROM CPFS
SELECT * FROM #TEMP
ORDER BY DDS_CPFCNPJ


