--Precisamos dos clientes que tentamos contato em todos os telefones e em todos tivemos um resultado de telefonia. Ação 785, 786 e 787 Santander Cap Débito Conta.
--Por gentileza, enviar CPF, Nome e os telefones com o ultimo status de cada telefone.
SELECT TOP 1 * FROM TB_CLIENTE WITH(NOLOCK) 
SELECT TOP 100 * FROM TB_CONTATO WITH(NOLOCK) 
SELECT * FROM TB_OCORRENCIA WITH(NOLOCK)
SELECT * FROM GRUPOOCORRENCIA WITH(NOLOCK)
SELECT TOP 1 * FROM TMKT..TB_ACAO WITH(NOLOCK)
SELECT TOP 1 * FROM TMKT..TB_CAMPANHA WITH(NOLOCK)
SELECT TOP 1 * FROM TB_ASSOCIADOS WITH(NOLOCK)
SELECT TOP 1 * FROM TB_DADOSCLI WITH(NOLOCK)
SELECT TOP 1 * FROM TB_TELEFONE WITH(NOLOCK)

	--EMITE RELATÓRIO DE CONTATOS EFETUADOS NO MÊS DE MAIO 2012 - SANTANDER CAP DÉBITO CONTA, QUE OBTIVERAM O RESULTADO DE TELEFONIA. 
	SELECT  DISTINCT DDS_NOME, 
					 DDS_CPFCNPJ,
					 FON_DDD1,					
		     ISNULL (FON_FONE1, '00000000') AS [TELEFONE 1],
		     ISNULL (FONE1.OCR_DESCRICAO, 'SEM TABULAÇÃO') AS [OCORRENCIA_TELEFONE_1],
					 FON_DDD2,
		     ISNULL (FON_FONE2, '00000000') AS [TELEFONE 2],
		     ISNULL (FONE2.OCR_DESCRICAO, 'SEM TABULAÇÃO') AS [OCORRENCIA_TELEFONE_2],
					 FON_DDD3,
		     ISNULL (FON_FONE3, '00000000') AS [TELEFONE 3],
		     ISNULL (FONE3.OCR_DESCRICAO, 'SEM TABULAÇÃO') AS [OCORRENCIA_TELEFONE_3],
					 FON_DDD4,	     
		     ISNULL (FON_FONE4, '00000000') AS [TELEFONE 4],
		     ISNULL (FONE4.OCR_DESCRICAO, 'SEM TABULAÇÃO') AS [OCORRENCIA_TELEFONE_4],
					 FON_DDD5,
		     ISNULL (FON_FONE5, '00000000') AS [TELEFONE 5],
		     ISNULL (FONE5.OCR_DESCRICAO, 'SEM TABULAÇÃO') AS [OCORRENCIA_TELEFONE_5],
		             ACO_CODIGO 
	--CRIANDO TABELA TEMPORÁRIO PARA REALIZAR FILTRO. 
	INTO #FILTRO
	FROM TB_CLIENTE INNER JOIN TB_CONTATO WITH(NOLOCK) ON CLI_CTOCODIGO = CTO_CODIGO --CTO_CLICODIGO = CLI_CODIGO 
					INNER JOIN TMKT..TB_CAMPANHA WITH(NOLOCK) ON (CMP_CODIGO = CLI_CMPCODIGO )
					INNER JOIN TMKT..TB_ACAO	 WITH(NOLOCK) ON (ACO_CODIGO = CMP_ACOCODIGO)
					INNER JOIN TB_DADOSCLI		 WITH(NOLOCK) ON (DDS_CLICODIGO = CLI_CODIGO)
					INNER JOIN TB_TELEFONE		 WITH(NOLOCK) ON  (FON_CLICODIGO = CTO_CLICODIGO)
					LEFT JOIN TB_OCORRENCIA FONE1 WITH(NOLOCK) ON (FONE1.OCR_GRUPO = CTO_GRUPO AND FONE1.OCR_SUBGRUPO = CTO_SUBGRUPO AND FONE1.OCR_OCORRENCIA = CTO_OCORRENCIA AND CTO_FONE = FON_FONE1 AND FONE1.OCR_GRUPO = 3 AND FONE1.OCR_SUBGRUPO = 1)
					LEFT JOIN TB_OCORRENCIA FONE2 WITH(NOLOCK) ON (FONE2.OCR_GRUPO = CTO_GRUPO AND FONE2.OCR_SUBGRUPO = CTO_SUBGRUPO AND FONE2.OCR_OCORRENCIA = CTO_OCORRENCIA AND CTO_FONE = FON_FONE2 AND FONE2.OCR_GRUPO = 3 AND FONE2.OCR_SUBGRUPO = 1)
					LEFT JOIN TB_OCORRENCIA FONE3 WITH(NOLOCK) ON (FONE3.OCR_GRUPO = CTO_GRUPO AND FONE3.OCR_SUBGRUPO = CTO_SUBGRUPO AND FONE3.OCR_OCORRENCIA = CTO_OCORRENCIA AND CTO_FONE = FON_FONE3 AND FONE3.OCR_GRUPO = 3 AND FONE3.OCR_SUBGRUPO = 1)
					LEFT JOIN TB_OCORRENCIA FONE4 WITH(NOLOCK) ON (FONE4.OCR_GRUPO = CTO_GRUPO AND FONE4.OCR_SUBGRUPO = CTO_SUBGRUPO AND FONE4.OCR_OCORRENCIA = CTO_OCORRENCIA AND CTO_FONE = FON_FONE4 AND FONE4.OCR_GRUPO = 3 AND FONE4.OCR_SUBGRUPO = 1)
					LEFT JOIN TB_OCORRENCIA FONE5 WITH(NOLOCK) ON (FONE5.OCR_GRUPO = CTO_GRUPO AND FONE5.OCR_SUBGRUPO = CTO_SUBGRUPO AND FONE5.OCR_OCORRENCIA = CTO_OCORRENCIA AND CTO_FONE = FON_FONE5 AND FONE5.OCR_GRUPO = 3 AND FONE5.OCR_SUBGRUPO = 1)
	WHERE ACO_CODIGO IN ('785','786','787') AND CTO_DATAHORA BETWEEN '2012-05-01 00:00:00'AND '2012-05-31 23:59:59' 
	ORDER BY ACO_CODIGO  ASC
	
	SELECT *  FROM #FILTRO
	
	
	
	--FILTRA E NÃO DEIXA EXIBIR OS REGISTROS QUE NÃO TENHAM NENHUMA TABULAÇÃO VÁLIDA.
	SELECT * FROM #FILTRO
	WHERE 
		OCORRENCIA_TELEFONE_1 NOT IN('SEM TABULAÇÃO') OR 
		OCORRENCIA_TELEFONE_2 NOT IN('SEM TABULAÇÃO')OR 
		OCORRENCIA_TELEFONE_3 NOT IN('SEM TABULAÇÃO') OR 
		OCORRENCIA_TELEFONE_4 NOT IN('SEM TABULAÇÃO') OR 
		OCORRENCIA_TELEFONE_5 NOT IN('SEM TABULAÇÃO')
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	SELECT DISTINCT 

DDS_NOME, 

DDS_CPFCNPJ, 

ISNULL (FON_FONE1, '00000000') AS [TELEFONE 1],

ISNULL (FONE1.OCR_DESCRICAO, 'SEM TABULAO') AS [OCORRENCIA_TELEFONE_1],

ISNULL (FON_FONE2, '00000000') AS [TELEFONE 2],

ISNULL (FONE2.OCR_DESCRICAO, 'SEM TABULAO') AS [OCORRENCIA_TELEFONE_2],

ISNULL (FON_FONE3, '00000000') AS [TELEFONE 3],

ISNULL (FONE3.OCR_DESCRICAO, 'SEM TABULAO') AS [OCORRENCIA_TELEFONE_3],

ISNULL (FON_FONE4, '00000000') AS [TELEFONE 4],

ISNULL (FONE4.OCR_DESCRICAO, 'SEM TABULAO') AS [OCORRENCIA_TELEFONE_4],

ISNULL (FON_FONE5, '00000000') AS [TELEFONE 5],

ISNULL (FONE5.OCR_DESCRICAO, 'SEM TABULAO') AS [OCORRENCIA_TELEFONE_5],

ACO_CODIGO

INTO #RESUMO

FROM TB_CLIENTE WITH(NOLOCK)

INNER JOIN TB_CONTATO WITH(NOLOCK) ON CLI_CTOCODIGO = CTO_CODIGO --CTO_CLICODIGO = CLI_CODIGO 

--INNER JOIN TB_OCORRENCIA WITH(NOLOCK) ON (CTO_GRUPO = OCR_GRUPO AND CTO_SUBGRUPO = OCR_SUBGRUPO AND CTO_OCORRENCIA = OCR_OCORRENCIA)

INNER JOIN TMKT..TB_CAMPANHA WITH(NOLOCK) ON (CMP_CODIGO = CLI_CMPCODIGO )

INNER JOIN TMKT..TB_ACAO WITH(NOLOCK) ON (ACO_CODIGO = CMP_ACOCODIGO)

INNER JOIN TB_DADOSCLI WITH(NOLOCK) ON (DDS_CLICODIGO = CLI_CODIGO)

INNER JOIN TB_TELEFONE WITH(NOLOCK) ON (FON_CLICODIGO = CTO_CLICODIGO)

LEFT JOIN TB_OCORRENCIA FONE1 WITH(NOLOCK) ON (FONE1.OCR_GRUPO = CTO_GRUPO AND FONE1.OCR_SUBGRUPO = CTO_SUBGRUPO AND FONE1.OCR_OCORRENCIA = CTO_OCORRENCIA AND CTO_FONE = FON_FONE1 AND FONE1.OCR_GRUPO = 3 AND FONE1.OCR_SUBGRUPO = 1)

LEFT JOIN TB_OCORRENCIA FONE2 WITH(NOLOCK) ON (FONE2.OCR_GRUPO = CTO_GRUPO AND FONE2.OCR_SUBGRUPO = CTO_SUBGRUPO AND FONE2.OCR_OCORRENCIA = CTO_OCORRENCIA AND CTO_FONE = FON_FONE2 AND FONE2.OCR_GRUPO = 3 AND FONE2.OCR_SUBGRUPO = 1)

LEFT JOIN TB_OCORRENCIA FONE3 WITH(NOLOCK) ON (FONE3.OCR_GRUPO = CTO_GRUPO AND FONE3.OCR_SUBGRUPO = CTO_SUBGRUPO AND FONE3.OCR_OCORRENCIA = CTO_OCORRENCIA AND CTO_FONE = FON_FONE3 AND FONE3.OCR_GRUPO = 3 AND FONE3.OCR_SUBGRUPO = 1)

LEFT JOIN TB_OCORRENCIA FONE4 WITH(NOLOCK) ON (FONE4.OCR_GRUPO = CTO_GRUPO AND FONE4.OCR_SUBGRUPO = CTO_SUBGRUPO AND FONE4.OCR_OCORRENCIA = CTO_OCORRENCIA AND CTO_FONE = FON_FONE4 AND FONE4.OCR_GRUPO = 3 AND FONE4.OCR_SUBGRUPO = 1)

LEFT JOIN TB_OCORRENCIA FONE5 WITH(NOLOCK) ON (FONE5.OCR_GRUPO = CTO_GRUPO AND FONE5.OCR_SUBGRUPO = CTO_SUBGRUPO AND FONE5.OCR_OCORRENCIA = CTO_OCORRENCIA AND CTO_FONE = FON_FONE5 AND FONE5.OCR_GRUPO = 3 AND FONE5.OCR_SUBGRUPO = 1)

WHERE ACO_CODIGO IN ('785','786','787') AND CTO_DATAHORA BETWEEN '2012-05-01 00:00:00'AND '2012-05-31 23:59:59' 

ORDER BY ACO_CODIGO ASC


-- carregando s as pessoas que tem tabulação da tabela #com_tabulacao

SELECT * 

INTO #COM_TABULACAO

FROM #RESUMO WITH(NOLOCK)

WHERE 

OCORRENCIA_TELEFONE_1 NOT IN('SEM TABULAO') OR 

OCORRENCIA_TELEFONE_2 NOT IN('SEM TABULAO') OR 

OCORRENCIA_TELEFONE_3 NOT IN('SEM TABULAO') OR 

OCORRENCIA_TELEFONE_4 NOT IN('SEM TABULAO') OR 

OCORRENCIA_TELEFONE_5 NOT IN('SEM TABULAO')


-- aqui era um exemplo para buscar as pessoas que no tinham tabulação

SELECT A.* FROM #RESUMO A WITH(NOLOCK)

LEFT JOIN #COM_TABULACAO B WITH(NOLOCK) ON A.DDS_NOME = B.DDS_NOME

WHERE B.DDS_NOME IS NULL


	
	
	
	
	SELECT  DISTINCT DDS_NOME, 
					 DDS_CPFCNPJ,					
		     ISNULL (FON_FONE1, '00000000') AS [TELEFONE 1],
		     ISNULL (FONE1.OCR_DESCRICAO, 'NULL') AS [OCORRÊNCIA TELEFONE 1],
		     ISNULL (FON_FONE2, '00000000') AS [TELEFONE 2],
		     ISNULL (FONE2.OCR_DESCRICAO, 'NULL') AS [OCORRÊNCIA TELEFONE 2],
		     ISNULL (FON_FONE3, '00000000') AS [TELEFONE 3],
		     ISNULL (FONE3.OCR_DESCRICAO, 'NULL') AS [OCORRÊNCIA TELEFONE 3],
		     ISNULL (FON_FONE4, '00000000') AS [TELEFONE 4],
		     ISNULL (FONE4.OCR_DESCRICAO, 'NULL') AS [OCORRÊNCIA TELEFONE 4],
		     ISNULL (FON_FONE5, '00000000') AS [TELEFONE 5],
		     ISNULL (FONE5.OCR_DESCRICAO, 'NULL') AS [OCORRÊNCIA TELEFONE 5],
		             ACO_CODIGO 
	FROM TB_CLIENTE INNER JOIN TB_CONTATO		 WITH(NOLOCK) ON CLI_CTOCODIGO = CTO_CODIGO --CTO_CLICODIGO = CLI_CODIGO 
					--INNER JOIN TB_OCORRENCIA	 WITH(NOLOCK) ON (CTO_GRUPO = OCR_GRUPO AND CTO_SUBGRUPO = OCR_SUBGRUPO AND CTO_OCORRENCIA = OCR_OCORRENCIA)
					INNER JOIN TMKT..TB_CAMPANHA WITH(NOLOCK) ON (CMP_CODIGO = CLI_CMPCODIGO )
					INNER JOIN TMKT..TB_ACAO	 WITH(NOLOCK) ON (ACO_CODIGO = CMP_ACOCODIGO)
					INNER JOIN TB_DADOSCLI		 WITH(NOLOCK) ON (DDS_CLICODIGO = CLI_CODIGO)
					INNER JOIN TB_TELEFONE		 WITH(NOLOCK) ON (FON_CLICODIGO = CTO_CLICODIGO)
					LEFT JOIN TB_OCORRENCIA FONE1 WITH(NOLOCK) ON (FONE1.OCR_GRUPO = CTO_GRUPO AND FONE1.OCR_SUBGRUPO = CTO_SUBGRUPO AND FONE1.OCR_OCORRENCIA = CTO_OCORRENCIA AND CTO_FONE = FON_FONE1 AND FONE1.OCR_GRUPO = 3 AND FONE1.OCR_SUBGRUPO = 1)
					LEFT JOIN TB_OCORRENCIA FONE2 WITH(NOLOCK) ON (FONE2.OCR_GRUPO = CTO_GRUPO AND FONE2.OCR_SUBGRUPO = CTO_SUBGRUPO AND FONE2.OCR_OCORRENCIA = CTO_OCORRENCIA AND CTO_FONE = FON_FONE2 AND FONE2.OCR_GRUPO = 3 AND FONE2.OCR_SUBGRUPO = 1)
					LEFT JOIN TB_OCORRENCIA FONE3 WITH(NOLOCK) ON (FONE3.OCR_GRUPO = CTO_GRUPO AND FONE3.OCR_SUBGRUPO = CTO_SUBGRUPO AND FONE3.OCR_OCORRENCIA = CTO_OCORRENCIA AND CTO_FONE = FON_FONE3 AND FONE3.OCR_GRUPO = 3 AND FONE3.OCR_SUBGRUPO = 1)
					LEFT JOIN TB_OCORRENCIA FONE4 WITH(NOLOCK) ON (FONE4.OCR_GRUPO = CTO_GRUPO AND FONE4.OCR_SUBGRUPO = CTO_SUBGRUPO AND FONE4.OCR_OCORRENCIA = CTO_OCORRENCIA AND CTO_FONE = FON_FONE4 AND FONE4.OCR_GRUPO = 3 AND FONE4.OCR_SUBGRUPO = 1)
					LEFT JOIN TB_OCORRENCIA FONE5 WITH(NOLOCK) ON (FONE5.OCR_GRUPO = CTO_GRUPO AND FONE5.OCR_SUBGRUPO = CTO_SUBGRUPO AND FONE5.OCR_OCORRENCIA = CTO_OCORRENCIA AND CTO_FONE = FON_FONE5 AND FONE5.OCR_GRUPO = 3 AND FONE5.OCR_SUBGRUPO = 1)
	WHERE ACO_CODIGO IN ('785','786','787') AND CTO_DATAHORA BETWEEN '2012-05-01 00:00:00'AND '2012-05-31 23:59:59' 
		  AND (FONE1.OCR_DESCRICAO IS NOT NULL) AND FONE2.OCR_DESCRICAO IS NOT NULL AND FONE3.OCR_DESCRICAO IS NOT NULL AND FONE4.OCR_DESCRICAO IS NOT NULL AND FONE5.OCR_DESCRICAO IS NOT NULL
	
	
	SELECT TOP 10  * FROM TB_TELEFONE 
	WHERE FON_SEQ1 IS NOT NULL
	
	
	
