CREATE TABLE TESTE_MOISES
(
	ID INT IDENTITY(1,1),
	CAD_APLICACAO INT,
	IMAGEM VARBINARY(MAX),
)

DECLARE @SQL VARCHAR(8000) -- variavel que vai receber o comando sql
DECLARE @ARQUIVO VARCHAR(MAX) -- recebe o caminho do arquivo.
SET @ARQUIVO = '\\ip_da_maquina\c$\Documents and Settings\134744\Desktop\IMG_1.JPG'

DECLARE @NOME_FOTO VARCHAR(150)

SET @NOME_FOTO = 'FOTO_1'

SET @SQL = ''      
SET @SQL = @SQL + 'INSERT INTO TESTE_MOISES (CAD_APLICACAO,NOME,DATA,IMAGEM)'      
		SET @SQL = @SQL + 'SELECT  ''' + @NOME_FOTO+''',''JONATHAN'','+CONVERT(VARCHAR,GETDATE(),103)     
		SET @SQL = @SQL + ', BULKCOLUMN FROM OPENROWSET( BULK ''' + @ARQUIVO +''', SINGLE_BLOB)'

print(@SQL)


INSERT INTO TESTE_MOISES (CAD_APLICACAO,IMAGEM,NOME,DATA)
SELECT 



INSERT INTO TESTE_MOISES (CAD_APLICACAO,NOME,DATA,IMAGEM)
SELECT  1,NOME,DATA,BULKCOLUMN FROM OPENROWSET( BULK '\\ip_da_maquina\c$\Documents and Settings\134744\Desktop\IMG_1.JPG', SINGLE_BLOB)



INSERT INTO TESTE_MOISES (CAD_APLICACAO,NOME,DATA,IMAGEM)
SELECT  1,'JONATHAN',09/05/2012, BULKCOLUMN FROM OPENROWSET( BULK '\\ip_da_maquina\c$\Documents and Settings\134744\Desktop\IMG_1.JPG', SINGLE_BLOB)



INSERT INTO TESTE_MOISES (CAD_APLICACAO,NOME,DATA,IMAGEM)
SELECT  FOTO_1,'JONATHAN',09/05/2012, BULKCOLUMN FROM OPENROWSET( BULK '\\ip_da_maquina\c$\Documents and Settings\134744\Desktop\IMG_1.JPG', SINGLE_BLOB)



INSERT INTO TESTE_MOISES (CAD_APLICACAO,NOME,DATA,IMAGEM)
SELECT  'FOTO_1','JONATHAN',09/05/2012, BULKCOLUMN FROM OPENROWSET( BULK '\\ip_da_maquina\c$\Documents and Settings\134744\Desktop\IMG_1.JPG', SINGLE_BLOB)




