--MOSTRANDO AS HORA ATUAL E UMA HORA ADIATADA.
--MOSTRANTANDO A HORA ATUAL.
SELECT CONVERT(VARCHAR,GETDATE(),108)
--MOSTRANDO A HORA ATUAL UMA HORA DEPOIS.
SELECT CONVERT(VARCHAR, DATEADD(HOUR,1,GETDATE()), 108)

--MOSTRANDO A DATA ATUAL E UM DIA ADIANTADO. 
--MOSTRANDO A DATA ATUAL 
SELECT CONVERT(VARCHAR, GETDATE(), 103)
--MOSTRANDO O DIA ATUAL UM DIA DEPOIS. 
SELECT CONVERT(VARCHAR, DATEADD(DAY, 1,GETDATE()), 103)

--MOSTRANDO O ANO ATUAL E ANO ADIANTADO. 
--MOSTRANDO O ANO ATUAL
SELECT  CONVERT(VARCHAR, GETDATE(), 103)
--MOSTRANDO O ANO ATUAL UM ANO DEPOIS.
SELECT CONVERT(VARCHAR, DATEADD(YEAR, 1, GETDATE()), 103)