SELECT TOP 100 * INTO #TB_DADOSCLI  FROM [TB_DADOSCLI]
SELECT TOP 100 * INTO #TB_ENDERECO  FROM [TB_ENDERECO]
SELECT TOP 100 * INTO #TB_TELEFONE  FROM [TB_TELEFONE]
SELECT TOP 100 * INTO #TB_CLIENTE   FROM [TB_CLIENTE]

SELECT * FROM #TB_DADOSCLI
SELECT * FROM #TB_ENDERECO
SELECT * FROM #TB_TELEFONE
SELECT * FROM #TB_CLIENTE

--	CALULAR A SOMA DO CLICODIGO  E CALCULAR O PERCENTUAL DOS CLICODIGOS SOMADOS.
	SELECT SUM(DDS_CLICODIGO) AS SOMA_CLICODIGO, SUM(DDS_CLICODIGO) * 0.19 AS PERCENTUAL_CLICODIGO
	FROM #TB_DADOSCLI

--	CALCULAR A MÉDIA DOS CLICODIGOS ABAIXO DE 10600.
SELECT AVG(DDS_CLICODIGO) AS MEDIA_CLICODIGO
FROM #TB_DADOSCLI
WHERE DDS_CLICODIGO < 10600

SELECT AVG(DDS_CLICODIGO) AS MEDIA_CLICODIGO
FROM #TB_DADOSCLI
 
--*AGRUPANDO A INFORMAÇÃO
SELECT DDS_CLICODIGO, DDS_NOME
FROM #TB_DADOSCLI
GROUP BY DDS_CLICODIGO, DDS_NOME

--SELECT COUNT(0), CONVERT(VARCHAR,CLI_DATAHORA,103) FROM TB_CLIENTE WITH(NOLOCK)
--WHERE CLI_DATAHORA BETWEEN '2012-04-01' AND '2012-04-20 23:59:59'
--GROUP BY CONVERT(VARCHAR,CLI_DATAHORA,103)
--ORDER BY CONVERT(VARCHAR,CLI_DATAHORA,103)

--GROUP BY
--	AGRUPAR OS CLIENTES CADASTRADOS ENTRE A DATA '2010-08-13'E '2010-08-13 14:10:33.367'
SELECT COUNT(*) AS QTD_CLIENTES_CADASTRADOS, CONVERT(VARCHAR, DDS_DATAHORA, 103)AS DATA_ESPECIFICADA FROM #TB_DADOSCLI WITH(NOLOCK)
WHERE DDS_DATAHORA BETWEEN '2010-08-13' AND '2010-08-13 14:10:33.367'
GROUP BY CONVERT(VARCHAR, DDS_DATAHORA, 103) 
ORDER BY CONVERT(VARCHAR, DDS_DATAHORA, 103)

--	CONTE  OS QUANTOS CLIENTES FORAM CADASTRADO NAS DATAS EXISTENTES NOS REGISTROS. 
SELECT COUNT(*) AS QTD_CLIENTES_CADASTRADOS, CONVERT(VARCHAR, DDS_DATAHORA, 103) AS DATA_E_HORA 
FROM #TB_DADOSCLI WITH(NOLOCK) 
GROUP BY CONVERT(VARCHAR, DDS_DATAHORA, 103)
ORDER BY CONVERT(VARCHAR, DDS_DATAHORA, 103)

--	CONTE A QUANTIDADE DE REGISTROS DE CLIENTES, QUE NASCERAM DA DATA: '1956-04-19 00:00:00.000'
SELECT COUNT(*) AS QTD_CLIENTES_CADASTRADOS, CONVERT(VARCHAR, DDS_DATANASC, 103) AS DATA_NASC
FROM #TB_DADOSCLI
WHERE DDS_DATANASC = '1956-04-19 00:00:00.000'
GROUP BY CONVERT(VARCHAR, DDS_DATANASC, 103)


--SELECT DENTRO DE OUTRO SELECT
--	MOSTRAR O CODIGO E NOME DO ÚLTIMO CLIENTE CADASTRADO. 
SELECT DDS_NOME, DDS_CLICODIGO FROM #TB_DADOSCLI WITH(NOLOCK) WHERE DDS_CLICODIGO IN (SELECT MAX(DDS_CLICODIGO) FROM #TB_DADOSCLI)


SELECT * FROM #TB_DADOSCLI
SELECT * FROM #TB_ENDERECO
SELECT * FROM #TB_TELEFONE
SELECT * FROM #TB_CLIENTE

SELECT COUNT(DDS_CLICODIGO) AS QTDE_FONES_APARECE, DDS_NOME, END_ENDERECO, FON_FONE1
FROM #TB_DADOSCLI 
INNER JOIN #TB_ENDERECO WITH(NOLOCK)ON DDS_CLICODIGO = END_CLICODIGO
INNER JOIN #TB_TELEFONE WITH(NOLOCK)ON DDS_CLICODIGO = FON_CLICODIGO
GROUP BY DDS_NOME, END_ENDERECO, FON_FONE1

SELECT COUNT(DDS_NOME)AS QUANTIDADE_NOMES,
MAX(END_ENDERECO)AS PRIMEIRO_ENDERECO, MIN(FON_FONE1)AS ULTIMO_TELEFONE,
CONVERT(VARCHAR, DDS_DATAHORA, 103) AS DATA_ESPECIFICADA
FROM #TB_DADOSCLI INNER JOIN #TB_ENDERECO WITH(NOLOCK)ON DDS_CLICODIGO = END_CLICODIGO
INNER JOIN #TB_TELEFONE WITH(NOLOCK)ON DDS_CLICODIGO = FON_CLICODIGO
WHERE DDS_DATAHORA BETWEEN '2010-08-13 14:10:33.367' AND '2010-08-16 10:37:06.743'
GROUP BY CONVERT(VARCHAR, DDS_DATAHORA, 103)
ORDER BY COUNT(DDS_NOME) DESC
--PODE SER TMABÉM (ORDER BY CONVERT(VARCHAR, DDS_DATAHORA, 103) DESC OU ASC)


--CLAÚSULA HAVING 
SELECT COUNT(DDS_CLICODIGO)
FROM #TB_DADOSCLI
GROUP BY DDS_CLICODIGO 
HAVING COUNT(DDS_CLICODIGO) < 2
