SELECT TOP 100 * INTO #TB_DADOSCLI  FROM [TB_DADOSCLI]
SELECT TOP 100 * INTO #TB_ENDERECO  FROM [TB_ENDERECO]
SELECT TOP 100 * INTO #TB_TELEFONE  FROM [TB_TELEFONE]
SELECT TOP 100 * INTO #TB_CLIENTE   FROM [TB_CLIENTE]

SELECT * FROM #TB_DADOSCLI
SELECT * FROM #TB_ENDERECO
SELECT * FROM #TB_TELEFONE
SELECT * FROM #TB_CLIENTE


--GROUP BY
--	CONTAR A QUANTIDADE DE NOMES TEM NA TABELA #TB_DADOSCLI
SELECT DDS_NOME, COUNT(*) AS CONTAGEM_DE_NOMES_IGUAIS
FROM #TB_DADOSCLI
GROUP BY DDS_NOME

--	CONTANDO OS ENDEREÇO IGUAIS QUE EXISTEM NA TABELA
SELECT END_ENDERECO, COUNT(*) AS [CONTADOR DE ENDERECOS IGUAIS]
FROM #TB_ENDERECO
GROUP BY END_ENDERECO

--UPDATE
--	FAZENDO ALTERAÇÃO DO NOME DO CLIENTE NA TABELA #TB_DADOSCLI
UPDATE #TB_DADOSCLI SET DDS_NOME = 'MOISÉS SALVADOR'
WHERE DDS_NOME = 'JOEL SILVA DO NASCIMENTO'

--ALTERANDO O NOME E CPF DO CLIENTE DA TABELA #TB_DADOSCLI , ATRAVÉS DO CLICODIGO. 
UPDATE #TB_DADOSCLI SET DDS_NOME = 'SALOMAO DA SILVA', DDS_CPFCNPJ = '1111111'
WHERE DDS_CLICODIGO = 1

--DELETANDO UM REGISTRO DE UMA TABELA
DELETE 
FROM #TB_DADOSCLI 
WHERE DDS_CLICODIGO = 1

--ADICIONANDO UMA NOVA COLUNA EM UMA TABELA.
-- ADICIONAR UM COLUNA NOVA CHAMADA COLUNA_TESTES  
ALTER TABLE #TB_DADOSCLI ADD TELEFONE_TRABALHO VARCHAR(15)
--	ADICIONAR UMA COLUNA NOVA CHAMADA COLUNA_NOVA
ALTER TABLE #TB_DADOSCLI ADD COLUNA_NOVA FLOAT 

--EXCLUINDO UMA COLUNA DE UMA TABLEA
--	EXCLUIR A COLUNA COLUNA_TESTES
ALTER TABLE #TB_DADOSCLI
DROP COLUMN COLUNA_TESTES
--	EXCLUIR A COLUNA COLUNA_NOVA
ALTER TABLE #TB_DADOSCLI
DROP COLUMN COLUNA_NOVA

--ADICICONANDO CONTEÚDO DENTRO DA COLUNA NOVA PARA TODAS AS PESSOAS QUE COMEÇAM COM A LETRA "M"
UPDATE #TB_DADOSCLI SET TELEFONE_TRABALHO = '(11)-6481-6215'
WHERE DDS_NOME LIKE 'M%'


SELECT * FROM #TB_DADOSCLI
SELECT * FROM #TB_ENDERECO
SELECT * FROM #TB_TELEFONE
SELECT * FROM #TB_CLIENTE

--CRIANDO UM INDICE DA TABELA DADOSCLI
CREATE NONCLUSTERED INDEX INDEX_DDS_CLICODIGO ON #TB_DADOSCLI(DDS_CLICODIGO);
CREATE NONCLUSTERED INDEX INDEX_END_CODIGO ON #TB_ENDERECO(END_CODIGO);

--OPERADORES RELACIONAIS 
--	SELECIONANDO CLIENTES POR MEIO DE OPERADORES RELACIONAIS. 
SELECT DDS_CLICODIGO, DDS_NOME FROM #TB_DADOSCLI
WHERE DDS_CLICODIGO > 10 AND DDS_CLICODIGO < 90

--	SELECIONAR O NOME E ENDEREÇO DOS USUÁRIOS QUE TENHA O CÓDIGO ABAIXO DE 50.
SELECT DDS_CLICODIGO, DDS_NOME, END_ENDERECO FROM #TB_DADOSCLI 
INNER JOIN #TB_ENDERECO WITH(NOLOCK) ON DDS_CLICODIGO = END_CLICODIGO
WHERE DDS_CLICODIGO < 50

--	SELECIONAR O NOME, ENDEREÇO E TELEFONE DOS CODIGOS DE CLIENTES ABAIXO OU IGUAL A 50 E COLOCAR O NOME EM ORDEM CRESCENTE E ENDERECO NA 
--	ORDEM DECRESENTE. 
SELECT DDS_CLICODIGO, DDS_NOME, END_ENDERECO, FON_FONE1 FROM #TB_DADOSCLI
INNER JOIN #TB_ENDERECO WITH(NOLOCK) ON DDS_CLICODIGO = END_CLICODIGO
INNER JOIN #TB_TELEFONE WITH(NOLOCK) ON DDS_CLICODIGO = FON_CLICODIGO
WHERE DDS_CLICODIGO <= 50 
ORDER BY DDS_CLICODIGO ASC, END_ENDERECO DESC

--	SELECIONE O NOME E ENDEREÇO DOS CLIENTES QUE COMEÇAM COM A LETRA M E COLOCÁ-LOS EM ORDEM.  
SELECT DDS_NOME,END_ENDERECO FROM #TB_DADOSCLI
INNER JOIN #TB_ENDERECO WITH(NOLOCK) ON DDS_CLICODIGO = END_CLICODIGO
WHERE NOT DDS_NOME LIKE 'M%'
ORDER BY DDS_NOME

--  SELECIONAR O NOME, DATA DE NASC E ENDEREÇO DOS CLICODIGOS ACIMA DE 10 E ABAIXO DE 90
SELECT DDS_NOME, DDS_DATANASC, END_ENDERECO FROM #TB_DADOSCLI
INNER JOIN #TB_ENDERECO WITH(NOLOCK) ON DDS_CLICODIGO = END_CLICODIGO
WHERE DDS_CLICODIGO >10 AND DDS_CLICODIGO < 90

--BETWEEN 
--	SELECIONE O CLICODIGO, NOME, DATA DE NASCIMENTO E ENDEREÇO DOS CLICODIGOS QUE ESTEJAM ENTRE 10 E 90
SELECT DDS_CLICODIGO, DDS_NOME, DDS_DATANASC, END_ENDERECO FROM #TB_DADOSCLI
INNER JOIN #TB_ENDERECO WITH(NOLOCK) ON DDS_CLICODIGO = END_CLICODIGO
WHERE DDS_CLICODIGO BETWEEN 10 AND 90

--	SOMAR, TIRAR A MÉDIA DOS CLICODIGOS QUE ESTÃO ENTRE 10 E 90 DA TABELA #TB_DADOSCLI
SELECT SUM(DDS_CLICODIGO) AS SOMA_CLICODIGOS,
	   AVG(DDS_CLICODIGO) AS MEDIA_CLICODIGOS
FROM #TB_DADOSCLI 
WHERE DDS_CLICODIGO BETWEEN 10 AND 90



